### ISSUE TITLE
TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by silbernagel** [chartwerk/grafana-chartwerk-app#51] opened 2020-08-22 11:02 UTC
I'm running version 0.1.2, and just upgraded Grafana to 7.1.4. My old panels just went black, and when trying to add new ones, I get this error: 

"TypeError: Cannot read property 'emit' of undefined" Any tips/suggestions on what this is? Nothing in the grafana log, and the plugin is loaded fine according to the log.

**Comment by F4ncyMooN** [comment] 2020-08-27 07:12
Met same issue, my grafana version is 7.1.3

**Comment by balda** [comment] 2020-09-09 16:45
Mine is `TypeError: this.events is undefined` (7.1.5)

**Comment by rozetko** [comment] 2020-09-15 16:31
Hey @silbernagel @pojpojpoj @F4ncyMooN @balda, fixes are merged into master. It's possible to run the plugin from source if you want to test it

**Comment by rozetko** [comment] 2020-10-05 15:48
Hey @silbernagel @pojpojpoj @F4ncyMooN @balda, this issue is fixed in the new release: https://github.com/chartwerk/grafana-chartwerk-app/releases/tag/0.2.0

**Comment by rozetko** [comment] 2020-10-06 13:41
Got confirmation that the issue is fixed: https://github.com/chartwerk/grafana-chartwerk-app/issues/56#issuecomment-704270842

**Closed by rozetko** 2020-10-06 13:41 UTC
